config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_desdobramentos

  resources :desdobramentos do

    post :atributos_tipo, :on => :collection

  end

  resources :tipo_agressores

  resources :tipo_ocorrencias

  resources :encaminhamentos

  resources :ocorrencias do

    post :criar_pessoa, :on => :collection 

    get :autocomplete_pessoa_nome, :on => :collection

    post :desdobramento_tipo_ocorrencia, :on => :collection

    post :tipo_desdobramento_ocorrencia, :on => :collection

    post :desdobramento_tipo_agressor, :on => :collection

    post :tipo_desdobramento_agressor, :on => :collection


    get :autocomplete_tipo_desdobramento_ocorrencia_nome, :on => :collection

    get :autocomplete_tipo_agressor_nome, :on => :collection

  
  end

  resources :escolas

  resources :contatos

  resources :pessoas do

    post :atributos_documento, :on => :collection

    post :atributos_deficiente, :on => :collection    
      
  end

  get 'home/index'
  get 'home/nao_autorizado'
  get 'home/estatisticas'
  
  resources :usuarios do

  	get :redefinir_senha

    get :autocomplete_escola_nome, :on => :collection

  end
  
  devise_for :users
  resources :users

  devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end



end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base

	has_many :contatos, dependent: :destroy

	has_many :ocorrencias, :source => :agredido

	has_many :agressoes, :source => :agressor
  #has_and_belongs_to_many :agressoes, :inverse_of => :agressores, :class_name => "Ocorrencia"

  before_save :verificar_documento_deficiente

	accepts_nested_attributes_for :contatos, allow_destroy: true

	validates_presence_of :nome, :data_nascimento, :sexo, :nome_responsavel

	validates_uniqueness_of :nome, :scope => [:data_nascimento]

	validates_presence_of :numero_documento, :if => :documento

	validates_presence_of :tipo_deficiencia, :if => :deficiente

	#validates_presence_of :contatos

  def verificar_documento_deficiente
  	if self.documento == false
  		self.numero_documento = nil
  		self.tipo_documento = nil
  	end
  	if self.deficiente == false
  		self.tipo_deficiencia = nil
  	end
  end

  before_save :maiusculas_sem_acentos

  def maiusculas_sem_acentos

    self.nome = ActiveSupport::Inflector.transliterate(self.nome).upcase if !self.nome.blank?  
    self.nome_responsavel = ActiveSupport::Inflector.transliterate(self.nome_responsavel).upcase if !self.nome_responsavel.blank?
    self.numero = ActiveSupport::Inflector.transliterate(self.numero).upcase if !self.numero.blank?
    self.complemento = ActiveSupport::Inflector.transliterate(self.complemento).upcase if !self.complemento.blank?

    self.logradouro = ActiveSupport::Inflector.transliterate(self.logradouro).upcase if !self.logradouro.blank?

    self.bairro = ActiveSupport::Inflector.transliterate(self.bairro).upcase if !self.bairro.blank?
    self.cidade = ActiveSupport::Inflector.transliterate(self.cidade).upcase if !self.cidade.blank?
    self.nome_social = ActiveSupport::Inflector.transliterate(self.nome_social).upcase if !self.nome_social.blank?
    
  end

end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]
  before_filter :colecoes
  load_and_authorize_resource :class=>"Pessoa", except: :create

  # GET /pessoas
  # GET /pessoas.json
  def index
    #@pessoas = Pessoa.all
    @q = Pessoa.ransack(params[:q])
    @pessoas = @q.result.accessible_by(current_ability).order('nome ASC').paginate(:page => params[:page], :per_page => @@per_page)
    

  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
    @contato = @pessoa.contatos.build
    
  end

  # GET /pessoas/1/edit
  def edit
    
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: @@msgs }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new, alert: @@msge }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: @@msgs }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit, alert: @@msge }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: @@msgs }
      format.json { head :no_content }
    end
  end
  
  def atributos_documento
    if params[:documento] == 'true'
      render :partial => "atributos_documento"
    else
      render :nothing => true
    end
  end

  def atributos_deficiente
    if params[:deficiente] == 'true'
      render :partial => "atributos_deficiente"
    else
      render :nothing => true
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :nome_social, :data_nascimento, :sexo, :raca, :escolaridade, 
                                      :documento, :tipo_documento, :numero_documento, :deficiente,
                                      :contato, :logradouro, :bairro, :cidade,
                                      :tipo_deficiencia, :nome_responsavel, :cep, :numero, :complemento,
                                      contatos_attributes: [:id, :tipo, :numero, :_destroy])
    end

    def colecoes
      @lista_booleans = [['NAO',false], ['SIM',true]]
      @lista_sexos = [['M','M'], ['F','F']]
      @lista_documentos = [['RG','RG'], ['CPF','CPF'], ['CT','CT'], ['CN','CN']]
      @lista_deficiencias = [['FISICA','FISICA'], ['VISUAL','VISUAL'], ['AUDITIVA','AUDITIVA'],
                             ['MENTAL','MENTAL'], ['MULTIPLAS','MULTIPLAS']]
      @lista_escolaridades = [['FUNDAMENTAL - INCOMPLETO','FUNDAMENTAL - INCOMPLETO'],
                             ['FUNDAMENTAL - COMPLETO','FUNDAMENTAL - COMPLETO'],
                             ['MEDIO - INCOMPLETO','MEDIO - INCOMPLETO'], 
                             ['MEDIO - COMPLETO','MEDIO - COMPLETO'],
                             ['SUPERIOR - INCOMPLETO','SUPERIOR - INCOMPLETO'],
                             ['SUPERIOR - COMPLETO','SUPERIOR - COMPLETO']]
      @lista_contatos = [['RESIDENCIAL','RESIDENCIAL'], ['CELULAR','CELULAR'], ['TRABALHO','TRABALHO']]
      @lista_racas = [['BRANCA','BRANCA'], ['PRETA','PRETA'], ['PARDA','PARDA'], ['INDIGENA','INDIGENA'],
                     ['AMARELA','AMARELA']]
      

    end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/pessoas/_atributos_deficiente.html.erb
<%= simple_fields_for :pessoa do |f| %>
	<%= f.input :tipo_deficiencia, collection: @lista_deficiencias, as: :select, :include_blank => false %>
	
<% end %>

app/views/pessoas/_atributos_documento.html.erb
<%= simple_fields_for :pessoa do |f| %>
	<%= f.input :tipo_documento, collection: @lista_documentos, as: :select, :include_blank => false %>
	<%= f.input :numero_documento %>
	
<% end %>

app/views/pessoas/_form.html.erb
<%= simple_nested_form_for(@pessoa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :nome_social, :label=>"Nome Social ou Apelido" %>
    <%= f.input :data_nascimento %>
    <%= f.input :sexo, collection: @lista_sexos, as: :select, :include_blank => true %>
    <%= f.input :raca, :label=>"Raça/Cor", collection: @lista_racas, as: :select, :include_blank => true %>
    <%= f.input :escolaridade, collection: @lista_escolaridades, as: :select, :include_blank => true %>

    <%= f.input :documento, collection: @lista_booleans, as: :select, :include_blank => true %>
    
    <div id="atributos_documento">

      <%if @pessoa.documento and @pessoa.documento==true%>
        <%= f.input :tipo_documento, collection: @lista_documentos, as: :select, :include_blank => true %>
        <%= f.input :numero_documento %>
      <%end%>
      
    </div>

    <%= f.input :deficiente, collection: @lista_booleans, as: :select, :include_blank => true %>

    <div id="atributos_deficiente">

      <%if @pessoa.deficiente and @pessoa.deficiente==true%>
        <%= f.input :tipo_deficiencia, collection: @lista_deficiencias, as: :select, :include_blank => true %>
      <%end%>
      
    </div>    
    
    <%= f.input :nome_responsavel %>
    
    <%= f.input :logradouro %>
    <%= f.input :numero %>
    <%= f.input :bairro %>
    <%= f.input :cidade %>
    <%= f.input :cep %>
    
    <%= f.input :contato %>
    

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-primary' %>
    <%= link_to 'Voltar', pessoas_path, :class=>'btn btn-default' %>
  </div>

<% end %>

app/views/pessoas/edit.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Editando Pessoa <%= link_icone('editar') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/pessoas/form_pessoas_old.html.erb
<%= simple_nested_form_for(@pessoa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :data_nascimento %>
    <%= f.input :sexo, collection: @lista_sexos, as: :select, :include_blank => true %>
    <%= f.input :raca, :label=>"Raça/Cor", collection: @lista_racas, as: :select, :include_blank => true %>
    <%= f.input :escolaridade, collection: @lista_escolaridades, as: :select, :include_blank => true %>

    <%= f.input :documento, collection: @lista_booleans, as: :select, :include_blank => true %>
    
    <div id="atributos_documento">

      <%if @pessoa.documento and @pessoa.documento==true%>
        <%= f.input :tipo_documento, collection: @lista_documentos, as: :select, :include_blank => true %>
        <%= f.input :numero_documento %>
      <%end%>
      
    </div>

    <%= f.input :deficiente, collection: @lista_booleans, as: :select, :include_blank => true %>

    <div id="atributos_deficiente">

      <%if @pessoa.deficiente and @pessoa.deficiente==true%>
        <%= f.input :tipo_deficiencia, collection: @lista_deficiencias, as: :select, :include_blank => true %>
      <%end%>
      
    </div>    
    
    <%= f.input :nome_responsavel %>
    <%= f.input :cep %>
    <%= f.input :numero %>
    <%= f.input :complemento %>

    <div id="contatos">
      <%= f.fields_for :contatos, :wrapper => false, :html=>{:class=>"form-inline"} do |cf| %>
        <div class="fields">
          <%= cf.input :tipo,  :label=>"Tipo Contato", collection: @lista_contatos, as: :select, :include_blank => true %>
          <%= cf.input :numero %>
          <div class="pull-right">
            <%= cf.link_to_remove link_icone2("apagar","Remover Contato"), :class=>'btn btn-danger' %>
          </div>
          <br/>
        </div>
      <% end %>
    </div>
    <div class="form-actions">
      <%= f.link_to_add link_icone2("novo","Adicionar Contato"), :contatos, :data => { :target => "#contatos" }, :class=>'btn btn-success' %>
    </div>
    <br/>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-primary' %>
    <%= link_to 'Voltar', pessoas_path, :class=>'btn btn-default' %>
  </div>

<% end %>

app/views/pessoas/index.html.erb
<%- model_class = User -%>

<% content_for :titulo do %>
  <ul class="list-inline pull-right">
    <%= search_form_for @q, :url=>pessoas_url,  :class=>'navbar-form navbar-right', :role=>'search' do |f| %>
      
      <!-- NOVO -->
      <%= link_to link_icone('nova'), new_pessoa_path, :class=> 'btn btn-success', :title=>"Nova Pessoa" %>
      <!-- /NOVO -->

      <%= f.search_field :nome_cont, :class=>'form-control', :placeholder=>'Nome' %>
      <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>

    <% end %>
  </ul>
  <h4>
    <strong>
      Lista de Pessoas <i class="glyphicon glyphicon-user"></i>
    </strong>
  </h4>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      <th>Tipo documento</th>
      <th>Numero documento</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= data_br(pessoa.data_nascimento) %></td>
        <td><%= detalhes(pessoa.tipo_documento) %></td>
        <td><%= detalhes(pessoa.numero_documento) %></td>
        <td>
          <%= link_to link_icone('detalhes'),
                    pessoa_path(pessoa), :class => 'btn btn-default', :title=>"Detalhes" %>
          <%= link_to link_icone('editar'),
                    edit_pessoa_path(pessoa), :class => 'btn btn-primary', :title=>"Editar" %>
          <% if can? :delete, pessoa %>
            <%= link_to link_icone('apagar'), pessoa_path(pessoa), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' }, :title=>"Apagar" %> 
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<center>
  <%= will_paginate @pessoas, renderer: BootstrapPagination::Rails %>
</center>

app/views/pessoas/new.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Nova Pessoa <%= link_icone('novo') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/pessoas/show.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Detalhes da Pessoa <%= link_icone('detalhes') %>
    </strong>
  </h4>
<% end %>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Nome Social ou Apelido:</strong>
  <%= detalhes(@pessoa.nome_social) %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= data_br(@pessoa.data_nascimento) %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @pessoa.sexo %>
</p>

<p>
  <strong>Raça/Cor:</strong>
  <%= @pessoa.raca %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @pessoa.escolaridade %>
</p>

<p>
  <strong>Documento:</strong>
  <%= simnao(@pessoa.documento) %>
</p>


<% if @pessoa.documento == true %>

  <p>
    <strong>Tipo documento:</strong>
    <%= @pessoa.tipo_documento %>
  </p>

  <p>
    <strong>Numero documento:</strong>
    <%= @pessoa.numero_documento %>
  </p>

<% end %>

<p>
  <strong>Deficiente:</strong>
  <%= simnao(@pessoa.deficiente) %>
</p>

<% if @pessoa.deficiente == true %>

  <p>
    <strong>Tipo deficiencia:</strong>
    <%= @pessoa.tipo_deficiencia %>
  </p>

<% end %>

<p>
  <strong>Nome responsavel:</strong>
  <%= @pessoa.nome_responsavel %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= detalhes(@pessoa.logradouro) %>
</p>

<p>
  <strong>Numero:</strong>
  <%= detalhes(@pessoa.numero) %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= detalhes(@pessoa.bairro) %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= detalhes(@pessoa.cidade) %>
</p>

<p>
  <strong>Cep:</strong>
  <%= detalhes(@pessoa.cep) %>
</p>

<p>
  <strong>Contato:</strong>
  <%= detalhes(@pessoa.contato) %>
</p>

<%= link_to link_icone('voltar'), pessoas_path, :class=>'btn btn-default', :title=>"Voltar" %> 
<%= link_to link_icone('editar'), edit_pessoa_path(@pessoa), :class=>"btn btn-primary", :title=>"Editar" %> 
<%= link_to link_icone('nova'), new_pessoa_path, :class=> 'btn btn-success', :title=>"Nova Pessoa" %>