config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_desdobramentos

  resources :desdobramentos do

    post :atributos_tipo, :on => :collection

  end

  resources :tipo_agressores

  resources :tipo_ocorrencias

  resources :encaminhamentos

  resources :ocorrencias do

    post :criar_pessoa, :on => :collection 

    get :autocomplete_pessoa_nome, :on => :collection

    post :desdobramento_tipo_ocorrencia, :on => :collection

    post :tipo_desdobramento_ocorrencia, :on => :collection

    post :desdobramento_tipo_agressor, :on => :collection

    post :tipo_desdobramento_agressor, :on => :collection


    get :autocomplete_tipo_desdobramento_ocorrencia_nome, :on => :collection

    get :autocomplete_tipo_agressor_nome, :on => :collection

  
  end

  resources :escolas

  resources :contatos

  resources :pessoas do

    post :atributos_documento, :on => :collection

    post :atributos_deficiente, :on => :collection    
      
  end

  get 'home/index'
  get 'home/nao_autorizado'
  get 'home/estatisticas'
  
  resources :usuarios do

  	get :redefinir_senha

    get :autocomplete_escola_nome, :on => :collection

  end
  
  devise_for :users
  resources :users

  devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end



end

app/controllers/tipo_agressores_controller.rb
class TipoAgressoresController < ApplicationController
  before_action :set_tipo_agressor, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :class=>"TipoAgressor", except: :create
  # GET /tipo_agressores
  # GET /tipo_agressores.json
  def index
    #@tipo_agressores = TipoAgressor.all
    @q = TipoAgressor.ransack(params[:q])
    @tipo_agressores = @q.result.accessible_by(current_ability).order('descricao ASC').paginate(:page => params[:page], :per_page => @@per_page)
    
  end

  # GET /tipo_agressores/1
  # GET /tipo_agressores/1.json
  def show
  end

  # GET /tipo_agressores/new
  def new
    @tipo_agressor = TipoAgressor.new
  end

  # GET /tipo_agressores/1/edit
  def edit
  end

  # POST /tipo_agressores
  # POST /tipo_agressores.json
  def create
    @tipo_agressor = TipoAgressor.new(tipo_agressor_params)

    respond_to do |format|
      if @tipo_agressor.save
        format.html { redirect_to @tipo_agressor, notice: @@msgs }
        format.json { render :show, status: :created, location: @tipo_agressor }
      else
        format.html { render :new }
        format.json { render json: @tipo_agressor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_agressores/1
  # PATCH/PUT /tipo_agressores/1.json
  def update
    respond_to do |format|
      if @tipo_agressor.update(tipo_agressor_params)
        format.html { redirect_to @tipo_agressor, notice: @@msgs }
        format.json { render :show, status: :ok, location: @tipo_agressor }
      else
        format.html { render :edit }
        format.json { render json: @tipo_agressor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_agressores/1
  # DELETE /tipo_agressores/1.json
  def destroy
    @tipo_agressor.destroy
    respond_to do |format|
      format.html { redirect_to tipo_agressores_url, notice: @@msgs }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_agressor
      @tipo_agressor = TipoAgressor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_agressor_params
      params.require(:tipo_agressor).permit(:descricao)
    end
end

app/helpers/tipo_agressores_helper.rb
module TipoAgressoresHelper
end

app/views/tipo_agressores/_form.html.erb
<%= simple_form_for(@tipo_agressor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :descricao %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-primary' %>
    <%= link_to 'Voltar', tipo_agressores_path, :class=>'btn btn-default' %>
  </div>
<% end %>

app/views/tipo_agressores/edit.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Editando Tipo de Agressor <%= link_icone('editar') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/tipo_agressores/index.html.erb
<%- model_class = TipoAgressor -%>

<% content_for :titulo do %>
  <ul class="list-inline pull-right">
    <%= search_form_for @q, :url=>tipo_agressores_url,  :class=>'navbar-form navbar-right', :role=>'search' do |f| %>
      
      <!-- NOVO -->
      <%= link_to link_icone('novo'), new_tipo_agressor_path, :class=> 'btn btn-success', :title=>"Novo Tipo Agressor" %>
      <!-- /NOVO -->

      <%= f.search_field :descricao_cont, :class=>'form-control', :placeholder=>'Descricao' %>
      <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>

    <% end %>
  </ul>
  <h4>
    <strong>
      Lista de Tipos de Agressores <i class="glyphicon glyphicon-ok"></i>
    </strong>
  </h4>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_agressores.each do |tipo_agressor| %>
      <tr>
        <td><%= tipo_agressor.descricao %></td>
        <td>
          <%= link_to link_icone('detalhes'),
                    tipo_agressor_path(tipo_agressor), :class => 'btn btn-default', :title=>"Detalhes" %>
          <%= link_to link_icone('editar'),
                    edit_tipo_agressor_path(tipo_agressor), :class => 'btn btn-primary', :title=>"Editar" %>
          <% if can? :delete, tipo_agressor %>
            <%= link_to link_icone('apagar'), tipo_agressor_path(tipo_agressor), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' }, :title=>"Apagar" %> 
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<center>
  <%= will_paginate @tipo_agressores, renderer: BootstrapPagination::Rails %>
</center>

app/views/tipo_agressores/new.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Novo Tipo de Agressor <%= link_icone('novo') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/tipo_agressores/show.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Detalhes do Tipo de Agressor <%= link_icone('detalhes') %>
    </strong>
  </h4>
<% end %>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_agressor.descricao %>
</p>

<%= link_to link_icone('voltar'), tipo_agressores_path, :class=>'btn btn-default', :title=>"Voltar" %> 
<%= link_to link_icone('editar'), edit_tipo_agressor_path(@tipo_agressor), :class=>"btn btn-primary", :title=>"Editar" %> 
<%= link_to link_icone('nova'), new_tipo_agressor_path, :class=> 'btn btn-success', :title=>"Novo Tipo de Agressor" %>