config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_desdobramentos

  resources :desdobramentos do

    post :atributos_tipo, :on => :collection

  end

  resources :tipo_agressores

  resources :tipo_ocorrencias

  resources :encaminhamentos

  resources :ocorrencias do

    post :criar_pessoa, :on => :collection 

    get :autocomplete_pessoa_nome, :on => :collection

    post :desdobramento_tipo_ocorrencia, :on => :collection

    post :tipo_desdobramento_ocorrencia, :on => :collection

    post :desdobramento_tipo_agressor, :on => :collection

    post :tipo_desdobramento_agressor, :on => :collection


    get :autocomplete_tipo_desdobramento_ocorrencia_nome, :on => :collection

    get :autocomplete_tipo_agressor_nome, :on => :collection

  
  end

  resources :escolas

  resources :contatos

  resources :pessoas do

    post :atributos_documento, :on => :collection

    post :atributos_deficiente, :on => :collection    
      
  end

  get 'home/index'
  get 'home/nao_autorizado'
  get 'home/estatisticas'
  
  resources :usuarios do

  	get :redefinir_senha

    get :autocomplete_escola_nome, :on => :collection

  end
  
  devise_for :users
  resources :users

  devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end



end

app/models/tipo_desdobramento.rb
class TipoDesdobramento < ActiveRecord::Base
	belongs_to :desdobramento

	has_many :tipo_desdobramento_ocorrencias, :source => :tipo_desdobramento_ocorrencia
	has_many :tipo_desdobramento_agressores, :source => :tipo_desdobramento_agressor

	validates_presence_of :descricao, :desdobramento_id
	validates_uniqueness_of :descricao, :scope => [:desdobramento_id]

	before_save :maiusculas_sem_acentos

	def maiusculas_sem_acentos

		self.descricao = ActiveSupport::Inflector.transliterate(self.descricao).upcase if !self.descricao.blank?
		
	end

end

app/controllers/tipo_desdobramentos_controller.rb
class TipoDesdobramentosController < ApplicationController
  before_action :set_tipo_desdobramento, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :class=>"TipoDesdobramento", except: :create
  
  # GET /tipo_desdobramentos
  # GET /tipo_desdobramentos.json
  def index
    #@tipo_desdobramentos = TipoDesdobramento.all
    #@desdobramentos = Desdobramento.all
    @q = TipoDesdobramento.ransack(params[:q])
    @tipo_desdobramentos = @q.result.accessible_by(current_ability).order('descricao ASC').paginate(:page => params[:page], :per_page => @@per_page)
    
  end

  # GET /tipo_desdobramentos/1
  # GET /tipo_desdobramentos/1.json
  def show
  end

  # GET /tipo_desdobramentos/new
  def new
    @tipo_desdobramento = TipoDesdobramento.new
  end

  # GET /tipo_desdobramentos/1/edit
  def edit
  end

  # POST /tipo_desdobramentos
  # POST /tipo_desdobramentos.json
  def create
    @tipo_desdobramento = TipoDesdobramento.new(tipo_desdobramento_params)

    respond_to do |format|
      if @tipo_desdobramento.save
        format.html { redirect_to @tipo_desdobramento, notice: @@msgs }
        format.json { render :show, status: :created, location: @tipo_desdobramento }
      else
        format.html { render :new }
        format.json { render json: @tipo_desdobramento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_desdobramentos/1
  # PATCH/PUT /tipo_desdobramentos/1.json
  def update
    respond_to do |format|
      if @tipo_desdobramento.update(tipo_desdobramento_params)
        format.html { redirect_to @tipo_desdobramento, notice: @@msgs }
        format.json { render :show, status: :ok, location: @tipo_desdobramento }
      else
        format.html { render :edit }
        format.json { render json: @tipo_desdobramento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_desdobramentos/1
  # DELETE /tipo_desdobramentos/1.json
  def destroy
    @tipo_desdobramento.destroy
    respond_to do |format|
      format.html { redirect_to tipo_desdobramentos_url, notice: @@msgs }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_desdobramento
      @tipo_desdobramento = TipoDesdobramento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_desdobramento_params
      params.require(:tipo_desdobramento).permit(:descricao, :desdobramento_id)
    end
end

app/helpers/tipo_desdobramentos_helper.rb
module TipoDesdobramentosHelper
end

app/views/tipo_desdobramentos/_form.html.erb
<%= simple_form_for(@tipo_desdobramento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :desdobramento, collection: Desdobramento.order([:descricao]), :label=>"Desdobramento", label_method: :descricao_completa, value_method: :id, include_blank: false %>
    <%= f.input :descricao %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-primary' %>
    <%= link_to 'Voltar', tipo_desdobramentos_path, :class=>'btn btn-default' %>
  </div>
<% end %>

app/views/tipo_desdobramentos/edit.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Editando Tipo de Desdobramento <%= link_icone('editar') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/tipo_desdobramentos/index.html.erb
<%- model_class = TipoDesdobramento -%>

<% content_for :titulo do %>
  <ul class="list-inline pull-right">
    <%= search_form_for @q, :url=>tipo_desdobramentos_url,  :class=>'navbar-form navbar-right', :role=>'search' do |f| %>
      
      <!-- NOVO -->
      <%= link_to link_icone('novo'), new_tipo_desdobramento_path, :class=> 'btn btn-success', :title=>"Novo Tipo de Desdobramento" %>
      <!-- /NOVO -->

      <%= f.search_field :descricao_cont, :class=>'form-control', :placeholder=>'Descrição' %>
      <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>

    <% end %>
  </ul>
  <h4>
    <strong>
      Lista de Tipos de Desdobramentos <i class="glyphicon glyphicon-ok"></i>
    </strong>
  </h4>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_desdobramentos.each do |tipo_desdobramento| %>
      <tr>
        <td>
          <%= detalhes2(tipo_desdobramento.desdobramento, :descricao_completa) %>
        </td>
        <td><%= tipo_desdobramento.descricao %></td>
        <td>
          <%= link_to link_icone('detalhes'),
                    tipo_desdobramento_path(tipo_desdobramento), :class => 'btn btn-default', :title=>"Detalhes" %>
          <%= link_to link_icone('editar'),
                    edit_tipo_desdobramento_path(tipo_desdobramento), :class => 'btn btn-primary', :title=>"Editar" %>
          <% if can? :delete, tipo_desdobramento %>
            <%= link_to link_icone('apagar'), tipo_desdobramento_path(tipo_desdobramento), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' }, :title=>"Apagar" %> 
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<center>
  <%= will_paginate @tipo_desdobramentos, renderer: BootstrapPagination::Rails %>
</center>

app/views/tipo_desdobramentos/new.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Novo Tipo de Desdobramento <%= link_icone('novo') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/tipo_desdobramentos/show.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Detalhes do Tipo de tipo_desdobramento <%= link_icone('detalhes') %>
    </strong>
  </h4>
<% end %>

<p>
  <strong>Tipo:</strong>
  <%= detalhes2(@tipo_desdobramento.desdobramento, :descricao_completa) %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_desdobramento.descricao %>
</p>

<%= link_to link_icone('voltar'), tipo_desdobramentos_path, :class=>'btn btn-default', :title=>"Voltar" %> 
<%= link_to link_icone('editar'), edit_tipo_desdobramento_path(@tipo_desdobramento), :class=>"btn btn-primary", :title=>"Editar" %> 
<%= link_to link_icone('nova'), new_tipo_desdobramento_path, :class=> 'btn btn-success', :title=>"Nova tipo_desdobramento" %>