config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_desdobramentos

  resources :desdobramentos do

    post :atributos_tipo, :on => :collection

  end

  resources :tipo_agressores

  resources :tipo_ocorrencias

  resources :encaminhamentos

  resources :ocorrencias do

    post :criar_pessoa, :on => :collection 

    get :autocomplete_pessoa_nome, :on => :collection

    post :desdobramento_tipo_ocorrencia, :on => :collection

    post :tipo_desdobramento_ocorrencia, :on => :collection

    post :desdobramento_tipo_agressor, :on => :collection

    post :tipo_desdobramento_agressor, :on => :collection


    get :autocomplete_tipo_desdobramento_ocorrencia_nome, :on => :collection

    get :autocomplete_tipo_agressor_nome, :on => :collection

  
  end

  resources :escolas

  resources :contatos

  resources :pessoas do

    post :atributos_documento, :on => :collection

    post :atributos_deficiente, :on => :collection    
      
  end

  get 'home/index'
  get 'home/nao_autorizado'
  get 'home/estatisticas'
  
  resources :usuarios do

  	get :redefinir_senha

    get :autocomplete_escola_nome, :on => :collection

  end
  
  devise_for :users
  resources :users

  devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end



end

app/models/ocorrencia.rb
class Ocorrencia < ActiveRecord::Base
	self.table_name = 'ocorrencias'

	attr_accessor :agredido_nome, :agressor_nome, 
							  :tipo_desdobramento_ocorrencia_nome, :tipo_agressor_nome

	belongs_to :tipo_ocorrencia
	belongs_to :tipo_agressor
	belongs_to :tipo_desdobramento_ocorrencia, :inverse_of => :tipo_desdobramento_ocorrencias, :class_name => "TipoDesdobramento"
	belongs_to :encaminhamento
	belongs_to :user
	belongs_to :escola

	belongs_to :agredido, :inverse_of => :ocorrencias, :class_name => "Pessoa"
	belongs_to :agressor, :inverse_of => :agressoes, :class_name => "Pessoa"
	#has_and_belongs_to_many :agressores, :inverse_of => :agressoes, :class_name => "Pessoa"

	validates_presence_of :data_ocorrencia, :sob_influencia, :encaminhamento_id, 
	                      :tipo_desdobramento_ocorrencia_id,
												:tipo_agressor_id, :agredido_id, :user_id, :local_ocorrencia

	#validates_presence_of :escola_id,	:message => "Você precisa estar atrelado a uma Escola"

	validates_presence_of :agredido_nome, :if => Proc.new{|p| p.agredido_id.blank?}, :message => "Voce deve selecionar um nome"

	validates_presence_of :tipo_desdobramento_ocorrencia_nome, :if => Proc.new{|p| p.tipo_desdobramento_ocorrencia_id.blank?}, :message => "Voce deve selecionar um tipo de ocorrencia"

	validates_presence_of :tipo_agressor_nome, :if => Proc.new{|p| p.tipo_agressor_id.blank?}, :message => "Voce deve selecionar um tipo de agressor"

	validates_uniqueness_of :numero_protocolo

	after_create :gerar_numero_protocolo

	def gerar_numero_protocolo
		self.numero_protocolo = "#{DateTime.now.year}/#{self.id}"
		self.save
	end
	
	before_save :maiusculas_sem_acentos

	def maiusculas_sem_acentos

		self.observacoes = ActiveSupport::Inflector.transliterate(self.observacoes).upcase if !self.observacoes.blank?  
		
	end

	#fazer os escopes....

end

app/controllers/ocorrencias_controller.rb
class OcorrenciasController < ApplicationController
  before_action :set_ocorrencia, only: [:show, :edit, :update, :destroy]
  before_filter :colecoes
  load_and_authorize_resource :class=>"Ocorrencia", except: :create

  # GET /ocorrencias
  # GET /ocorrencias.json

  def index
    #@ocorrencias = Ocorrencia.all
    @q = Ocorrencia.ransack(params[:q])
    @ocorrencias = @q.result.accessible_by(current_ability).order('created_at DESC').paginate(:page => params[:page], :per_page => @@per_page)

  end

  # GET /ocorrencias/1
  # GET /ocorrencias/1.json
  def show
  end

  def autocomplete_pessoa_nome
    term = params[:term]
    pessoas = Pessoa.where('nome ilike ?',"%#{term}%").order(:nome).all
    render :json => pessoas.map { |pessoa| {:id => pessoa.id,:label => pessoa.nome, :value => pessoa.nome} }
  end

  # GET /ocorrencias/new
  def new
    @ocorrencia = Ocorrencia.new
  end

  # GET /ocorrencias/1/edit
  def edit
    #@tipo_ocorrencia = @ocorrencia.tipo_ocorrencia
    #@desdobramentos_tipo_ocorrencia = @tipo_ocorrencia.desdobramentos.collect{|t| [t.descricao, t.id]} if @tipo_ocorrencia
    #@tipo_desdobramentos_ocorrencia = @ocorrencia.desdobramento_tipo_ocorrencia.tipo_desdobramentos.collect{|t| [t.descricao, t.id]} if @ocorrencia.desdobramento_tipo_ocorrencia
    #@tipo_agressor = @ocorrencia.tipo_agressor
    #@desdobramentos_tipo_agressor = @tipo_agressor.desdobramentos.collect{|t| [t.descricao, t.id]} if @tipo_agressor
    #@tipo_desdobramentos_ocorrencia = @ocorrencia.desdobramento_tipo_agressor.tipo_desdobramentos.collect{|t| [t.descricao, t.id]} if @ocorrencia.desdobramento_tipo_agressor
  end

  # POST /ocorrencias
  # POST /ocorrencias.json
  def create
    @ocorrencia = Ocorrencia.new(ocorrencia_params)

    respond_to do |format|
      if @ocorrencia.save
        format.html { redirect_to @ocorrencia, notice: @@msgs }
        format.json { render :show, status: :created, location: @ocorrencia }
      else
        format.html { render :new, alert: @@msge }
        format.json { render json: @ocorrencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocorrencias/1
  # PATCH/PUT /ocorrencias/1.json
  def update
    respond_to do |format|
      if @ocorrencia.update(ocorrencia_params)
        format.html { redirect_to @ocorrencia, notice: @@msgs }
        format.json { render :show, status: :ok, location: @ocorrencia }
      else
        format.html { render :edit, alert: @@msge }
        format.json { render json: @ocorrencia.errors, status: :unprocessable_entity }
      end
    end
  end

  def criar_pessoa
    @pessoa = Pessoa.new(pessoa_params)
    
    respond_to do |format|
      if @pessoa.save
        format.js  {render "pessoa_salva"}
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.js {render "pessoa_nao_salva"}
        #format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocorrencias/1
  # DELETE /ocorrencias/1.json
  def destroy
    @ocorrencia.destroy
    respond_to do |format|
      format.html { redirect_to ocorrencias_url, notice: @@msgs }
      format.json { head :no_content }
    end
  end

  def autocomplete_tipo_desdobramento_ocorrencia_nome
    term = params[:term]
    ocorrencias = TipoDesdobramento.where('descricao ilike ?',"%#{term}%").order(:descricao).all
    render :json => ocorrencias.map { |ocorrencia| {:id => ocorrencia.id,:label => ocorrencia.descricao, :value => ocorrencia.descricao} }
  end

  def autocomplete_tipo_agressor_nome
    term = params[:term]
    agressores = TipoAgressor.where('descricao ilike ?',"%#{term}%").order(:descricao).all
    render :json => agressores.map { |agressor| {:id => agressor.id,:label => agressor.descricao, :value => agressor.descricao} }


  end

  

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ocorrencia
    @ocorrencia = Ocorrencia.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ocorrencia_params
    params.require(:ocorrencia).permit(:numero_protocolo, :local_ocorrencia, :data_ocorrencia, 
                                       :horario_aproximado, :observacoes,
                                       :sob_influencia, :encaminhamento_id, 
                                       :tipo_agressor_id, 
                                       :agredido_id, :agressor_id,
                                       :tipo_desdobramento_ocorrencia_id,
                                       :user_id, :escola_id, :agredido_nome, 
                                       :agressor_nome, :tipo_agressor_nome,
                                       :tipo_desdobramento_ocorrencia_nome)
  end

  def pessoa_params
    params.require(:pessoa).permit(:nome, :observacoes, :data_nascimento, :sexo, :raca, :escolaridade,
                                   :documento, :tipo_documento, :numero_documento, :deficiente,
                                   :tipo_deficiencia, :nome_responsavel, :cep, :numero, :complemento,
                                   contatos_attributes: [:id, :tipo, :numero, :_destroy])
  end

    def colecoes
      @lista_influencias = [['NAO','NAO'], ['DROGAS LICITAS','DROGAS LICITAS'],
                           ['DROGAS ILICITAS','DROGAS ILICITAS']]
      @pessoa = Pessoa.new
      @lista_booleans = [['NAO',false], ['SIM',true]]
      @lista_sexos = [['M','M'], ['F','F']]
      @lista_documentos = [['RG','RG'], ['CPF','CPF'], ['CT','CT'], ['CN','CN']]
      @lista_deficiencias = [['FISICA','FISICA'], ['VISUAL','VISUAL'], ['AUDITIVA','AUDITIVA'], ['MENTAL','MENTAL'], ['MULTIPLAS','MULTIPLAS']]
      @lista_escolaridades = [['FUNDAMENTAL - INCOMPLETO','FUNDAMENTAL - INCOMPLETO'], ['FUNDAMENTAL - COMPLETO','FUNDAMENTAL - COMPLETO'], ['MEDIO - INCOMPLETO','MEDIO - COMPLETO'], ['SUPERIOR - INCOMPLETO','SUPERIOR - INCOMPLETO'], ['SUPERIOR - COMPLETO','SUPERIOR - COMPLETO']]
      @lista_contatos = [['RESIDENCIAL','RESIDENCIAL'], ['CELULAR','CELULAR'], ['TRABALHO','TRABALHO']]
      @lista_racas = [['BRANCA','BRANCA'], ['PRETA','PRETA'], ['PARDA','PARDA'], ['INDIGENA','INDIGENA'], ['AMARELA','AMARELA']]
      
      @lista_locais = ['SALA DE AULA','QUADRA DE ESPORTE','BIBLIOTECA','CORREDOR DA ESCOLA','VIA PUBLICA','SECRETARIA','SALA DE LEITURA','SALA DE ALMOXARIFADO','SALA DE INFORMATICA','TV ESCOLA','SANITARIO ALUNOS','SANITARIO ADMINISTRATIVO','SANITARIO FUNCIONARIOS','RECREIO COBERTO','CAMPO ESPORTIVO','REFEITORIO','AUDITORIO','COZINHA','SUPERVISAO PEDAGOGICA','SALA DOS PROFESSORES','DIRECAO']

      @agressores_cadastrados = TipoAgressor.order('descricao ASC').all
      @ocorrencias_cadastradas = TipoDesdobramento.order('descricao ASC').all
    end
end

app/helpers/ocorrencias_helper.rb
module OcorrenciasHelper
end

app/views/ocorrencias/_desdobramentos_tipo_agressor.html.erb
<%=simple_fields_for :ocorrencia do |f|%>
<%= f.input :desdobramento_tipo_agressor_id, collection: @desdobramentos, :label=>"Desdobramento do Agressor", include_blank: true %>  
<%end%>

<div id="tipo_desdobramento_agressor">

</div>


<script type="text/javascript">

jQuery(function($) {$("#ocorrencia_desdobramento_tipo_agressor_id").change(function() {
    // make a POST call and replace the content
    var desdobramento_tipo_agressor = $('#ocorrencia_desdobramento_tipo_agressor_id').val();
    jQuery.post(gon.suburi+"/ocorrencias/tipo_desdobramento_agressor/?desdobramento_tipo_agressor=" + desdobramento_tipo_agressor, function(data){
      $("#tipo_desdobramento_agressor").html(data);   
    });
  });
});

</script>

app/views/ocorrencias/_form.html.erb
<%= simple_form_for(@ocorrencia) do |f| %>
  <%= f.error_notification %>

  <div id="notice">

  </div>

  <div class="form-inputs">

    <%= f.input :local_ocorrencia, collection: @lista_locais.sort, :label=>"Local da Ocorrência", include_blank: true %>  

    <%= f.input :data_ocorrencia, :label=>"Data da Ocorrência" %>

    <%= f.input :horario_aproximado, :label=>"Horario Aproximado da Ocorrência", include_blank: true %>

    <div class="pull-right">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModalTipoOcorrencia">
        Lista de Tipo de Ocorrencias
      </button>
    </div>

    <%= f.input :tipo_desdobramento_ocorrencia_nome, :label=>"Selecione o Tipo de Ocorrência", :url => autocomplete_tipo_desdobramento_ocorrencia_nome_ocorrencias_path, :as => :autocomplete, :id_element => "#tipo_desdobramento_ocorrencia_id" ,:input_html=>{:value=>(@ocorrencia.tipo_desdobramento_ocorrencia.descricao if @ocorrencia.tipo_desdobramento_ocorrencia)}%>
    
    <%= f.input :tipo_desdobramento_ocorrencia_id, :as => :hidden, :input_html => { :id => "tipo_desdobramento_ocorrencia_id"} %>

    <%= f.input :observacoes, :label=>"Observações" %>


    <div class="row">
      <div class="col-md-12">
        <div class="row">

          <div class="col-md-6">
            <%= f.input :agredido_nome, :label=>"Selecione a Pessoa Agredida", :url => autocomplete_pessoa_nome_ocorrencias_path, :as => :autocomplete, :id_element => "#agredido_id" ,:input_html=>{:value=>(@ocorrencia.agredido.nome if @ocorrencia.agredido)}%>

            <%= f.input :agredido_id, :as => :hidden, :input_html => { :id => "agredido_id"} %>   
          </div>
          <div class="col-md-6">
            <%= f.input :agressor_nome, :label=>"Selecione o Agressor", :url => autocomplete_pessoa_nome_ocorrencias_path, :as => :autocomplete, :id_element => "#agressor_id" ,:input_html=>{:value=>(@ocorrencia.agressor.nome if @ocorrencia.agressor)}%>

            <%= f.input :agressor_id, :as => :hidden, :input_html => { :id => "agressor_id"} %>
          </div>
        </div>

        <%= link_to link_icone2('nova', 'Cadastrar Pessoa'), '#myModal', :class=> 'btn btn-success', :title=>"Nova Pessoa", :'data-toggle'=>"modal", :'data-target'=>"#myModal"  %>  


      </div>

    </div>

    <br/>

    <div class="pull-right">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModalTipoAgressor">
        Lista de Tipo de Agressores
      </button>
    </div>

    <%= f.input :tipo_agressor_nome, :label=>"Selecione o Tipo de Agressor", :url => autocomplete_tipo_agressor_nome_ocorrencias_path, :as => :autocomplete, :id_element => "#tipo_agressor_id" ,:input_html=>{:value=>(@ocorrencia.tipo_agressor.descricao if @ocorrencia.tipo_agressor)}%>

    <%= f.input :tipo_agressor_id, :as => :hidden, :input_html => { :id => "tipo_agressor_id"} %>

    <%= f.input :sob_influencia, collection: @lista_influencias, as: :select, :include_blank => true %>

    <%= f.association :encaminhamento, collection: Encaminhamento.order([:descricao]), :label=>"Encaminhamento", label_method: :descricao, value_method: :id, include_blank: true %>

  </div>

  <% if @ocorrencia.user_id.blank? %>
    <%= f.input :user_id, as: :hidden, :input_html=>{:value=>current_user.id} %>
    <%= f.input :escola_id, as: :hidden, :input_html=>{:value=>current_user.escola_id} %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-primary' %>
    <%= link_to 'Voltar', ocorrencias_path, :class=>'btn btn-default' %>
  </div>
<% end %>


<!-- Modal -->
<div class="modal fade" id="myModalTipoOcorrencia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Tipos de Ocorrencias Cadastradas</h4>
      </div>
      <div class="modal-body">
        <ol>
          <% @ocorrencias_cadastradas.each do |o| %>
            <li><%= o.descricao %></li>
          <% end %>
        </ol>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="myModalTipoAgressor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Tipos de Agressores Cadastrados</h4>
      </div>
      <div class="modal-body">
        <ol>
          <% @agressores_cadastrados.each do |a| %>
            <li><%= a.descricao %></li>
          <% end %>
        </ol>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <%= render "form_pessoa" %>
</div>

app/views/ocorrencias/_tipo_desdobramento_agressor.html.erb
<%=simple_fields_for :ocorrencia do |f|%>
<%= f.input :tipo_desdobramento_agressor_id, collection: @tipo_desdobramentos_agressor, :label=>"Tipo de Desdobramento do Agressor", include_blank: true ,:input_html=>{:id=>"tipo_desdobramento_agressor_id"}%>  
<%end%>

app/views/ocorrencias/edit.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Editando Ocorrência <%= link_icone('editar') %>
    </strong>
  </h4>
<% end %>

<%= render 'form' %>

app/views/ocorrencias/form.old.html.erb
<%= simple_form_for(@ocorrencia) do |f| %>
  <%= f.error_notification %>

  <div id="notice">

  </div>

  <div class="form-inputs">

    <%= f.input :local_ocorrencia, collection: @lista_locais, :label=>"Local da Ocorrência", include_blank: true %>  

    <%= f.input :data_ocorrencia, :label=>"Data da Ocorrência" %>

    <%= f.input :horario_aproximado, :label=>"Horario Aproximado da Ocorrência", include_blank: true %>

    <%= f.association :tipo_ocorrencia, collection: TipoOcorrencia.order([:descricao]), :label=>"Tipo de Ocorrência", label_method: :descricao, value_method: :id, include_blank: true, :input_html => {:id => "ocorrencia_tipo_ocorrencia", :value=>(@ocorrencia.tipo_ocorrencia if @ocorrencia.tipo_ocorrencia)} %>  

    <div id="desdobramento_tipo_ocorrencia">
      <%if !@ocorrencia.new_record?%>

        <%= f.input :desdobramento_tipo_ocorrencia_id, collection: @desdobramentos_tipo_ocorrencia, :label=>"Desdobramento da Ocorrência", include_blank: true if (!@ocorrencia.desdobramento_tipo_ocorrencia.nil? or (@ocorrencia.tipo_ocorrencia and @ocorrencia.tipo_ocorrencia.desdobramentos.any?))%>

        <div id="tipo_desdobramento_ocorrencia">
          <%= f.input :tipo_desdobramento_ocorrencia_id, collection: @ocorrencia.desdobramento_tipo_ocorrencia.tipo_desdobramentos.collect{|t|[t.descricao,t.id]}, :label=>"Tipo de Desdobramento da Ocorrência", include_blank: true ,:input_html=>{:id=>"tipo_desdobramento_ocorrencia_id"}   if (!@ocorrencia.tipo_desdobramento_ocorrencia.nil? or (@ocorrencia.desdobramento_tipo_ocorrencia and @ocorrencia.desdobramento_tipo_ocorrencia.tipo_desdobramentos.any?))%>  
        </div>


        <script type="text/javascript">

            jQuery(function($) {$("#ocorrencia_desdobramento_tipo_ocorrencia_id").change(function() {
              // make a POST call and replace the content
              var desdobramento_tipo_ocorrencia = $('#ocorrencia_desdobramento_tipo_ocorrencia_id').val();
              jQuery.post(gon.suburi+"/ocorrencias/tipo_desdobramento_ocorrencia/?desdobramento_tipo_ocorrencia=" + desdobramento_tipo_ocorrencia, function(data){
                $("#tipo_desdobramento_ocorrencia").html(data);   
              });
            });
          });

        </script>

      <% end %>
    </div>

    <%= f.input :observacoes, :label=>"Observações" %>


    <div class="row">
      <div class="col-md-12">
        <div class="row">

          <div class="col-md-6">
            <%= f.input :agredido_nome, :label=>"Selecione a Pessoa Agredida", :url => autocomplete_pessoa_nome_ocorrencias_path, :as => :autocomplete, :id_element => "#agredido_id" ,:input_html=>{:value=>(@ocorrencia.agredido.nome if @ocorrencia.agredido)}%>

            <%= f.input :agredido_id, :as => :hidden, :input_html => { :id => "agredido_id"} %>   
          </div>
          <div class="col-md-6">
            <%= f.input :agressor_nome, :label=>"Selecione o Agressor", :url => autocomplete_pessoa_nome_ocorrencias_path, :as => :autocomplete, :id_element => "#agressor_id" ,:input_html=>{:value=>(@ocorrencia.agressor.nome if @ocorrencia.agressor)}%>

            <%= f.input :agressor_id, :as => :hidden, :input_html => { :id => "agressor_id"} %>
          </div>
        </div>

        <%= link_to link_icone2('nova', 'Cadastrar Pessoa'), '#myModal', :class=> 'btn btn-success', :title=>"Nova Pessoa", :'data-toggle'=>"modal", :'data-target'=>"#myModal"  %>  


      </div>

    </div>

    <br/>

    <%= f.association :tipo_agressor, collection: TipoAgressor.order([:descricao]), :label=>"Tipo de Agressor", label_method: :descricao, value_method: :id, include_blank: true, :input_html => {:id => "ocorrencia_tipo_agressor", :value=>(@ocorrencia.tipo_agressor if @ocorrencia.tipo_agressor)} %>  

    <div id="desdobramento_tipo_agressor">
      <%if !@ocorrencia.new_record?%>

        <%= f.input :desdobramento_tipo_agressor_id, collection: @desdobramentos_tipo_agressor, :label=>"Desdobramento do Agressor", include_blank: true if (!@ocorrencia.desdobramento_tipo_agressor.nil? or (@ocorrencia.tipo_agressor and @ocorrencia.tipo_agressor.desdobramentos.any?))%>  

        <div id="tipo_desdobramento_agressor">
          <%= f.input :tipo_desdobramento_agressor_id, collection: @ocorrencia.desdobramento_tipo_agressor.tipo_desdobramentos.collect{|t|[t.descricao,t.id]}, :label=>"Tipo de Desdobramento do Agressor", include_blank: true ,:input_html=>{:id=>"tipo_desdobramento_agressor_id"} if (!@ocorrencia.tipo_desdobramento_agressor.nil? or (@ocorrencia.desdobramento_tipo_agressor and @ocorrencia.desdobramento_tipo_agressor.tipo_desdobramentos.any?))%>  
        </div>  


        <script type="text/javascript">

            jQuery(function($) {$("#ocorrencia_desdobramento_tipo_agressor_id").change(function() {
              // make a POST call and replace the content
              var desdobramento_tipo_agressor = $('#ocorrencia_desdobramento_tipo_agressor_id').val();
              jQuery.post(gon.suburi+"/ocorrencias/tipo_desdobramento_agressor/?desdobramento_tipo_agressor=" + desdobramento_tipo_agressor, function(data){
                $("#tipo_desdobramento_agressor").html(data);   
              });
            });
          });

        </script>

      <% end %>
    </div>

    <%= f.input :sob_influencia, collection: @lista_influencias, as: :select, :include_blank => false %>

    <%= f.association :encaminhamento, collection: Encaminhamento.order([:descricao]), :label=>"Encaminhamento", label_method: :descricao, value_method: :id, include_blank: true %>

  </div>

  <% if @ocorrencia.user_id.blank? %>
    <%= f.input :user_id, as: :hidden, :input_html=>{:value=>current_user.id} %>
    <%= f.input :escola_id, as: :hidden, :input_html=>{:value=>current_user.escola_id} %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-primary' %>
    <%= link_to 'Voltar', ocorrencias_path, :class=>'btn btn-default' %>
  </div>
<% end %>




<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <%= render "form_pessoa" %>
</div>

app/views/ocorrencias/show.html.erb
<% content_for :titulo do %>
  <h4>
    <strong>
      Detalhes da Ocorrência <%= link_icone('detalhes') %>
    </strong>
  </h4>
<% end %>

<p>
  <strong>Número protocolo:</strong>
  <%= @ocorrencia.numero_protocolo %>
</p>

<p>
  <strong>Local Ocorrência:</strong>
  <%= @ocorrencia.local_ocorrencia %>
</p>

<p>
  <strong>Data Ocorrência:</strong>
  <%= data_br(@ocorrencia.data_ocorrencia) %>
</p>

<p>
  <strong>Horario Aproximado da Ocorrência:</strong>
  <%= hora_br(@ocorrencia.horario_aproximado) %>
</p>

<p>
  <strong>Agredido:</strong>
  <%= detalhes2(@ocorrencia.agredido, :nome) %>
</p>

<p>
  <strong>Agressor:</strong>
  <%= detalhes2(@ocorrencia.agressor, :nome) %>
</p>

<p>
  <strong>Sob influência:</strong>
  <%= @ocorrencia.sob_influencia %>
</p>


<p>
  <strong>Tipo de Ocorrencia:</strong>
  <%= detalhes2(@ocorrencia.tipo_desdobramento_ocorrencia.desdobramento.tipo_ocorrencia, :descricao) %>
  <%= detalhes2(@ocorrencia.tipo_desdobramento_ocorrencia.desdobramento, :descricao) %>
  <%= detalhes2(@ocorrencia.tipo_desdobramento_ocorrencia, :descricao) %>
</p>

<p>
  <strong>Tipo de Agressor:</strong>
  <%= detalhes2(@ocorrencia.tipo_agressor, :descricao) %>
</p>

<p>
  <strong>Encaminhamento:</strong>
  <%= detalhes2(@ocorrencia.encaminhamento, :descricao) %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= detalhes2(@ocorrencia.user, :name) %>
</p>

<p>
  <strong>Escola:</strong>
  <%= detalhes2(@ocorrencia.escola, :nome) %>
</p>


<%= link_to link_icone('voltar'), ocorrencias_path, :class=>'btn btn-default', :title=>"Voltar" %> 
<%= link_to link_icone('editar'), edit_ocorrencia_path(@ocorrencia), :class=>"btn btn-primary", :title=>"Editar" %> 
<%= link_to link_icone('nova'), new_ocorrencia_path, :class=> 'btn btn-success', :title=>"Nova ocorrencia" %>